version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - mynetwork

  backend:
    build: backend/.
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    networks:
      - mynetwork

  frontend:
    build: frontend/.
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
