apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-docker-registry/your-repository:backend-${{ github.sha }}
          ports:
            - containerPort: 8080
        - name: database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: your-username
            - name: POSTGRES_PASSWORD
              value: your-password
            - name: POSTGRES_DB
              value: your-database-name
