name: AKS Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
    

      - name: Select Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group stageDevops --name stage

      - name: List directory contents
        run: ls -R

      - uses: Azure/k8s-deploy@v4
        with:
           action: deploy
           manifests: |
              manifests/backend-deployment.yaml
              manifests/backend-service.yaml

