name: AKS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
        
      - uses: Azure/aks-set-context@v1
        with:
           creds: '${{ secrets.AZURE_CREDENTIALS }}'
           cluster-name: stage
           resource-group: stageDevops
       

      - name: Select Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group stageDevops --name stage

      - name: Deploy database to AKS
        run: |
          kubectl apply -f manifests/db-deploment.yaml
          kubectl apply -f manifests/db-service.yaml

      - name: Deploy backend to AKS
        run: |
         kubectl apply -f manifests/backend-deploment.yaml
         kubectl apply -f manifests/backend-service.yaml

      - name: Deploy frontend to AKS
        run: |
         kubectl apply -f manifests/frontend-deploment.yaml
         kubectl apply -f manifests/frontend-service.yaml
