name: AKS Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
    

      - name: Select Azure subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group stageDevops --name stage
  

      - name: Deploy database to AKS
        run: |
          kubectl apply -f manifests/backdeployment.yaml
          kubectl apply -f manifests/backservice.yaml

      - name: Deploy backend to AKS
        run: |
          kubectl apply -f ./backend/kubernetes/deployment.yaml
          kubectl apply -f ./backend/kubernetes/service.yaml

      - name: Deploy frontend to AKS
        run: |
          kubectl apply -f ./frontend/kubernetes/deployment.yaml
          kubectl apply -f ./frontend/kubernetes/service.yaml

