name: CD back end && front end 

on:
  workflow_run:
    workflows: ["CI back end && front end"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push back end image
        run: |
          cd backend
          docker build --build-arg JAR_FILE=target/*.jar -t ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce .

      - name: Push back end image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:backend-app
      
      - name: Build and push front end image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:frontend-app

      - name: Build and push db
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:db